export const OFFICIAL_SOURCES = [
  {
    id: "ofac-2022-advisory",
    title: "Guidance on the Democratic People's Republic of Korea Information Technology Workers",
    publisher: "U.S. Treasury OFAC, U.S. State Department, FBI",
    date: "2022-05-16",
    url: "https://ofac.treasury.gov/media/923131/download?inline=",
    note: "Baseline red flags and due diligence measures for avoiding inadvertent hiring of DPRK IT workers.",
  },
  {
    id: "ic3-2023-advisory",
    title: "North Korean Tactics, Techniques, and Procedures for Revenue Generation",
    publisher: "ODNI CTIIC / FBI IC3",
    date: "2023-10-18",
    url: "https://www.ic3.gov/PSA/2023/PSA231018.pdf",
    note: "Updated indicators for fraudulent documents, proxy accounts, remote desktop use, and crypto payments.",
  },
  {
    id: "fbi-2025-extortion",
    title: "North Korean IT Workers Conducting Data Extortion",
    publisher: "FBI",
    date: "2025-01-23",
    url: "https://www.fbi.gov/investigate/cyber/alerts/2025/north-korean-it-workers-conducting-data-extortion",
    note: "Guidance on data theft, repository copying, session abuse, AI video, and remote hiring controls.",
  },
  {
    id: "ic3-2025-threats",
    title: "North Korean IT Worker Threats to U.S. Businesses",
    publisher: "FBI IC3",
    date: "2025-07-23",
    url: "https://www.ic3.gov/PSA/2025/PSA250723-4",
    note: "Public guidance on U.S.-based facilitators, laptop farms, report channels, and vendor exposure.",
  },
  {
    id: "doj-2025-nationwide",
    title: "Justice Department Announces Coordinated, Nationwide Actions to Combat North Korean Remote IT Workers",
    publisher: "U.S. Department of Justice",
    date: "2025-06-30",
    url: "https://www.justice.gov/opa/pr/justice-department-announces-coordinated-nationwide-actions-combat-north-korean-remote",
    note: "Charges, searches, account/domain seizures, and alleged blockchain-company crypto thefts.",
  },
  {
    id: "treasury-2026-facilitators",
    title: "Treasury Sanctions Facilitators of DPRK IT Worker Fraud Targeting U.S. Businesses",
    publisher: "U.S. Treasury OFAC",
    date: "2026-03-12",
    url: "https://home.treasury.gov/news/press-releases/sb0416",
    note: "Sanctions against facilitators and entities tied to DPRK IT worker fraud networks.",
  },
  {
    id: "doj-2026-wang-sentencing",
    title: "Two U.S. Nationals Sentenced for Facilitating Fraudulent Remote Information Technology Worker Scheme",
    publisher: "U.S. Department of Justice",
    date: "2026-04-15",
    url: "https://www.justice.gov/opa/pr/two-us-nationals-sentenced-facilitating-fraudulent-remote-information-technology-worker",
    note: "Sentencing announcement for U.S.-based laptop farm facilitators tied to DPRK remote IT worker fraud.",
  },
  {
    id: "doj-2025-chapman",
    title: "Arizona Woman Sentenced in $17M IT Worker Fraud Scheme",
    publisher: "U.S. Department of Justice",
    date: "2025-07-24",
    url: "https://www.justice.gov/usao-dc/pr/arizona-woman-sentenced-17m-it-worker-fraud-scheme-illegally-generated-revenue-north",
    note: "Sentencing announcement for a U.S.-based laptop farm scheme involving more than 300 companies.",
  },
  {
    id: "doj-2025-guilty-pleas",
    title: "Justice Department Announces Nationwide Actions to Combat Illicit North Korean Government Revenue Generation",
    publisher: "U.S. Department of Justice",
    date: "2025-11-14",
    url: "https://www.justice.gov/opa/pr/justice-department-announces-nationwide-actions-combat-illicit-north-korean-government",
    note: "Guilty pleas by U.S. and Ukrainian facilitators of DPRK remote IT worker schemes.",
  },
  {
    id: "treasury-2025-dept53",
    title: "Treasury Targets IT Worker Network Generating Revenue for DPRK Weapons Programs",
    publisher: "U.S. Treasury OFAC",
    date: "2025-01-16",
    url: "https://home.treasury.gov/news/press-releases/jy2790",
    note: "OFAC designations for Department 53, front companies, supervisors, and equipment suppliers.",
  },
  {
    id: "treasury-2025-sobaeksu",
    title: "Treasury Sanctions Clandestine IT Worker Network Funding the DPRK's Weapons Programs",
    publisher: "U.S. Treasury OFAC",
    date: "2025-07-24",
    url: "https://home.treasury.gov/news/press-releases/sb0205",
    note: "OFAC designations for Korea Sobaeksu Trading Company and associated individuals.",
  },
  {
    id: "treasury-2025-fraud-network",
    title: "Treasury Sanctions Fraud Network Funding DPRK Weapons Programs",
    publisher: "U.S. Treasury OFAC",
    date: "2025-08-27",
    url: "https://home.treasury.gov/news/press-releases/sb0230",
    note: "OFAC designations for a Chinyong-linked IT worker payment and front-company network.",
  },
  {
    id: "treasury-2025-bankers",
    title: "Treasury Sanctions DPRK Bankers and Institutions Involved in Laundering Cybercrime Proceeds and IT Worker Funds",
    publisher: "U.S. Treasury OFAC",
    date: "2025-11-04",
    url: "https://home.treasury.gov/news/press-releases/sb0302",
    note: "OFAC designations tied to cybercrime proceeds, IT worker funds, and DPRK IT delegations.",
  },
];

export const PUBLIC_CASES = [
  {
    id: "kim-kwang-jin-team",
    title: "FBI wanted: fraudulent remote IT worker team tied to blockchain theft",
    status: "Wanted by FBI; allegations unresolved unless proven in court",
    date: "2025-06-24",
    sourceId: "doj-2025-nationwide",
    names: [
      { name: "Kim Kwang Jin", aliases: ["P.S."] },
      { name: "Kang Tae Bok", aliases: ["Wong Shao Onn"] },
      { name: "Jong Pong Ju", aliases: ["Bryan Cho"] },
      { name: "Chang Nam Il", aliases: ["Bong Chee Shen", "Peter Xiao"] },
    ],
    photos: [
      {
        name: "Kim Kwang Jin",
        url: "https://www.fbi.gov/wanted/cyber/fraudulent-remote-it-workers-from-dprk/jin.jpg",
      },
      {
        name: "Kang Tae Bok",
        url: "https://www.fbi.gov/wanted/cyber/fraudulent-remote-it-workers-from-dprk/bok.jpg",
      },
      {
        name: "Jong Pong Ju",
        url: "https://www.fbi.gov/wanted/cyber/fraudulent-remote-it-workers-from-dprk/ju.jpg",
      },
      {
        name: "Chang Nam Il",
        url: "https://www.fbi.gov/wanted/cyber/fraudulent-remote-it-workers-from-dprk/il.jpg",
      },
    ],
    summary:
      "DOJ says four DPRK nationals used false or stolen identities to obtain remote IT roles and allegedly stole more than $900,000 in virtual currency from two companies.",
    indicators: ["False or stolen identities", "Remote IT roles at crypto companies", "Smart contract/source-code access", "Tornado Cash laundering allegations"],
    link: "https://www.fbi.gov/wanted/cyber/fraudulent-remote-it-workers-from-dprk",
  },
  {
    id: "jin-sung-il-pak-jin-song",
    title: "FBI wanted: multi-year remote IT worker fraud case",
    status: "Wanted by FBI; allegations unresolved unless proven in court",
    date: "2025-01-21",
    sourceId: "doj-2025-nationwide",
    names: [
      { name: "Jin Sung-Il", aliases: [] },
      { name: "Pak Jin-Song", aliases: [] },
    ],
    photos: [
      {
        name: "Jin Sung-Il",
        url: "https://www.fbi.gov/wanted/cyber/dprk-it-fraud/jin-sungil.jpeg",
      },
      {
        name: "Pak Jin-Song",
        url: "https://www.fbi.gov/wanted/cyber/dprk-it-fraud/pak-jin-song.jpeg",
      },
    ],
    summary:
      "DOJ says the defendants and co-conspirators obtained work from at least 64 U.S. companies, generated at least $866,255 from 10 companies, and laundered proceeds through a Chinese bank account.",
    indicators: ["Forged and stolen identity documents", "Laptop farm facilitation", "U.S. company remote jobs", "Money laundering allegations"],
    link: "https://www.fbi.gov/wanted/cyber/dprk-it-fraud",
  },
  {
    id: "missouri-14",
    title: "Fourteen DPRK nationals indicted in Yanbian Silverstar / Volasys Silverstar scheme",
    status: "Indicted; allegations unresolved unless proven in court",
    date: "2024-12-12",
    sourceId: "doj-2025-nationwide",
    names: [
      { name: "Jong Song Hwa", aliases: [] },
      { name: "Ri Kyong Sik", aliases: [] },
      { name: "Kim Ryu Song", aliases: [] },
      { name: "Rim Un Chol", aliases: [] },
      { name: "Kim Mu Rim", aliases: [] },
      { name: "Cho Chung Pom", aliases: [] },
      { name: "Hyon Chol Song", aliases: [] },
      { name: "Son Un Chol", aliases: [] },
      { name: "Sok Kwang Hyok", aliases: [] },
      { name: "Choe Jong Yong", aliases: [] },
      { name: "Ko Chung Sok", aliases: [] },
      { name: "Kim Ye Won", aliases: [] },
      { name: "Jong Kyong Chol", aliases: [] },
      { name: "Jang Chol Myong", aliases: [] },
    ],
    photos: [
      {
        name: "Jong Song Hwa",
        url: "https://www.fbi.gov/wanted/cyber/jong-song-hwa/%40%40images/image",
      },
      {
        name: "Ri Kyong Sik",
        url: "https://www.fbi.gov/wanted/cyber/ri-kyong-sik/%40%40images/image",
      },
      {
        name: "Kim Ryu Song",
        url: "https://www.fbi.gov/wanted/cyber/kim-ryu-song/%40%40images/image",
      },
      {
        name: "Rim Un Chol",
        url: "https://www.fbi.gov/wanted/cyber/rim-un-chol/%40%40images/image",
      },
      {
        name: "Kim Mu Rim",
        url: "https://www.fbi.gov/wanted/cyber/kim-mu-rim/%40%40images/image",
      },
      {
        name: "Cho Chung Pom",
        url: "https://www.fbi.gov/wanted/cyber/cho-chung-pom/%40%40images/image",
      },
      {
        name: "Hyon Chol Song",
        url: "https://www.fbi.gov/wanted/cyber/hyon-chol-song/%40%40images/image",
      },
      {
        name: "Son Un Chol",
        url: "https://www.fbi.gov/wanted/cyber/son-un-chol/%40%40images/image",
      },
      {
        name: "Sok Kwang Hyok",
        url: "https://www.fbi.gov/wanted/cyber/sok-kwang-hyok/%40%40images/image",
      },
      {
        name: "Choe Jong Yong",
        url: "https://www.fbi.gov/wanted/cyber/choe-jong-yong/%40%40images/image",
      },
      {
        name: "Ko Chung Sok",
        url: "https://www.fbi.gov/wanted/cyber/ko-chung-sok/%40%40images/image",
      },
      {
        name: "Kim Ye Won",
        url: "https://www.fbi.gov/wanted/cyber/kim-ye-won/%40%40images/image",
      },
      {
        name: "Jong Kyong Chol",
        url: "https://www.fbi.gov/wanted/cyber/jong-kyong-chol/%40%40images/image",
      },
      {
        name: "Jang Chol Myong",
        url: "https://www.fbi.gov/wanted/cyber/jang-chol-myong/%40%40images/image",
      },
    ],
    summary:
      "DOJ says the group worked for DPRK-controlled Yanbian Silverstar and Volasys Silverstar, using false, stolen, and borrowed identities to obtain remote IT work and launder revenue.",
    indicators: ["False, stolen, and borrowed identities", "Front companies", "Remote work contracts", "Revenue laundering allegations"],
    link: "https://www.fbi.gov/wanted/cyber/dprk-it-workers",
  },
  {
    id: "chinyong-kim-sang-man",
    title: "OFAC sanctions: Chinyong Information Technology Cooperation Company and Kim Sang Man",
    status: "OFAC-designated sanctions target",
    date: "2023-05-23",
    sourceId: "treasury-2023-chinyong",
    names: [
      { name: "Chinyong Information Technology Cooperation Company", aliases: ["Jinyong IT Cooperation Company"] },
      { name: "Kim Sang Man", aliases: [] },
    ],
    summary:
      "OFAC sanctioned Chinyong and Kim Sang Man for roles tied to DPRK overseas IT worker delegations, revenue generation, and cryptocurrency payments.",
    indicators: ["DPRK IT worker delegations", "Russia and Laos operations", "Cryptocurrency payment flows", "Sanctions designation"],
    link: "https://home.treasury.gov/news/press-releases/jy1498",
  },
  {
    id: "sim-hyon-sop",
    title: "DOJ charged Foreign Trade Bank representative Sim Hyon Sop in crypto laundering conspiracies",
    status: "Charged; allegations unresolved unless proven in court",
    date: "2023-04-24",
    sourceId: "doj-2023-sim",
    names: [{ name: "Sim Hyon Sop", aliases: ["Sim"] }],
    summary:
      "DOJ says Sim allegedly conspired with North Korean IT workers to launder proceeds from illegal IT development work at blockchain companies.",
    indicators: ["Blockchain development companies", "Stablecoin and virtual currency payments", "FTB-linked laundering allegations", "Sanctions evasion"],
    link: "https://www.justice.gov/opa/pr/north-korean-foreign-trade-bank-representative-charged-crypto-laundering-conspiracies",
  },
  {
    id: "ofac-2026-network",
    title: "OFAC 2026 sanctions: facilitators and entities tied to DPRK IT worker fraud",
    status: "OFAC-designated sanctions targets",
    date: "2026-03-12",
    sourceId: "treasury-2026-facilitators",
    names: [
      { name: "Amnokgang Technology Development Company", aliases: [] },
      { name: "Nguyen Quang Viet", aliases: [] },
      { name: "Quangvietdnbg International Services Company Limited", aliases: [] },
      { name: "Do Phi Khanh", aliases: [] },
      { name: "Hoang Van Nguyen", aliases: [] },
      { name: "Yun Song Guk", aliases: [] },
      { name: "Hoang Minh Quang", aliases: [] },
      { name: "York Louis Celestino Herrera", aliases: [] },
    ],
    summary:
      "OFAC designated six individuals and two entities for roles in DPRK IT worker schemes, including currency conversion, IT worker coordination, and facilitation services.",
    indicators: ["Currency conversion", "IT worker coordination", "Freelance IT contracts", "Sanctions designation"],
    link: "https://home.treasury.gov/news/press-releases/sb0416",
  },
  {
    id: "wang-laptop-farms",
    title: "DOJ sentencing: U.S.-based laptop farms that helped DPRK IT workers pose as U.S. residents",
    status: "Sentenced after guilty pleas",
    date: "2026-04-15",
    sourceId: "doj-2026-wang-sentencing",
    names: [
      { name: "Kejia Wang", aliases: [] },
      { name: "Zhenxing Wang", aliases: ["Danny Wang"] },
    ],
    summary:
      "DOJ says the defendants operated laptop farms that helped North Korean remote IT workers pose as U.S. residents, use stolen identities, and obtain work from more than 100 U.S. companies.",
    indicators: ["Laptop farms", "Stolen identities", "U.S.-resident impersonation", "More than 100 victim companies"],
    link: "https://www.justice.gov/opa/pr/two-us-nationals-sentenced-facilitating-fraudulent-remote-information-technology-worker",
  },
  {
    id: "chapman-laptop-farm",
    title: "Christina Marie Chapman laptop farm scheme",
    status: "Sentenced after guilty plea",
    date: "2025-07-24",
    sourceId: "doj-2025-chapman",
    names: [{ name: "Christina Marie Chapman", aliases: [] }],
    summary:
      "DOJ says Chapman assisted DPRK IT workers posing as U.S. residents, helped them work at 309 U.S. companies, and generated more than $17 million in illicit revenue.",
    indicators: ["Laptop farm", "Stolen U.S. identities", "309 U.S. companies", "Payroll and check laundering"],
    link: "https://www.justice.gov/usao-dc/pr/arizona-woman-sentenced-17m-it-worker-fraud-scheme-illegally-generated-revenue-north",
  },
  {
    id: "southern-georgia-facilitators",
    title: "U.S. facilitators who provided identities, hosted laptops, and passed vetting steps",
    status: "Guilty pleas",
    date: "2025-11-14",
    sourceId: "doj-2025-guilty-pleas",
    names: [
      { name: "Audricus Phagnasay", aliases: [] },
      { name: "Jason Salazar", aliases: [] },
      { name: "Alexander Paul Travis", aliases: [] },
    ],
    summary:
      "DOJ says the defendants provided U.S. identities, hosted victim company laptops, installed remote access software, and helped overseas IT workers pass employer vetting.",
    indicators: ["Identity lending", "Laptop hosting", "Unauthorized remote access software", "Drug-test substitution"],
    link: "https://www.justice.gov/opa/pr/justice-department-announces-nationwide-actions-combat-illicit-north-korean-government",
  },
  {
    id: "didenko-identity-market",
    title: "Oleksandr Didenko identity and account marketplace",
    status: "Guilty plea",
    date: "2025-11-10",
    sourceId: "doj-2025-guilty-pleas",
    names: [{ name: "Oleksandr Didenko", aliases: ["Alexander Didenko"] }],
    summary:
      "DOJ says Didenko stole U.S. identities and sold them to overseas IT workers, including DPRK IT workers, so they could fraudulently gain employment at 40 U.S. companies.",
    indicators: ["Stolen identity marketplace", "Freelance platform accounts", "Money-service accounts", "40 U.S. companies"],
    link: "https://www.justice.gov/opa/pr/justice-department-announces-nationwide-actions-combat-illicit-north-korean-government",
  },
  {
    id: "prince-ashtor-alonso",
    title: "Taggcar and facilitator indictment tied to 64-company remote IT worker scheme",
    status: "Indicted; one guilty plea reported by DOJ",
    date: "2025-01-23",
    sourceId: "doj-2025-guilty-pleas",
    names: [
      { name: "Pedro Ernesto Alonso De Los Reyes", aliases: [] },
      { name: "Erick Ntekereze Prince", aliases: [] },
      { name: "Emanuel Ashtor", aliases: [] },
    ],
    summary:
      "DOJ says the facilitators helped obtain work for DPRK IT workers from more than 64 U.S. companies; Erick Ntekereze Prince later pleaded guilty to wire fraud conspiracy.",
    indicators: ["Staffing-vendor facilitation", "False and stolen identities", "Laptop farm", "64 U.S. companies"],
    link: "https://www.justice.gov/opa/pr/two-north-korean-nationals-and-three-facilitators-indicted-multi-year-fraudulent-remote",
  },
  {
    id: "department-53-laos-network",
    title: "OFAC Department 53 / Laos IT worker network",
    status: "OFAC-designated sanctions targets",
    date: "2025-01-16",
    sourceId: "treasury-2025-dept53",
    names: [
      { name: "Department 53 of the Ministry of the People's Armed Forces", aliases: [] },
      { name: "Korea Osong Shipping Co", aliases: ["Osong"] },
      { name: "Chonsurim Trading Corporation", aliases: ["Chonsurim"] },
      { name: "Jong In Chol", aliases: [] },
      { name: "Son Kyong Sik", aliases: [] },
      { name: "Liaoning China Trade Industry Co., Ltd", aliases: ["Liaoning China Trade"] },
    ],
    summary:
      "OFAC says Department 53 and front companies maintained DPRK IT worker delegations in Laos and used aliases to generate revenue from IT projects including crypto exchanges, web apps, and mobile apps.",
    indicators: ["Laos IT worker delegations", "Aliases with clients", "Crypto exchange development", "Equipment supply network"],
    link: "https://home.treasury.gov/news/press-releases/jy2790",
  },
  {
    id: "sobaeksu-network",
    title: "OFAC Korea Sobaeksu IT worker and procurement network",
    status: "OFAC-designated sanctions targets",
    date: "2025-07-24",
    sourceId: "treasury-2025-sobaeksu",
    names: [
      { name: "Korea Sobaeksu Trading Company", aliases: ["Sobaeksu United Corporation"] },
      { name: "Kim Se Un", aliases: [] },
      { name: "Jo Kyong Hun", aliases: [] },
      { name: "Myong Chol Min", aliases: [] },
    ],
    summary:
      "OFAC says Sobaeksu and associated individuals helped evade sanctions and generate revenue through fraudulent IT worker schemes and related procurement activity.",
    indicators: ["IT worker deployment", "Vietnam-linked revenue activity", "Cryptocurrency and financial coordination", "Sanctions evasion"],
    link: "https://home.treasury.gov/news/press-releases/sb0205",
  },
  {
    id: "andreyev-geumpungri-sinjin",
    title: "OFAC Chinyong-linked payment and front-company network",
    status: "OFAC-designated sanctions targets",
    date: "2025-08-27",
    sourceId: "treasury-2025-fraud-network",
    names: [
      { name: "Vitaliy Sergeyevich Andreyev", aliases: [] },
      { name: "Kim Ung Sun", aliases: [] },
      { name: "Shenyang Geumpungri Network Technology Co., Ltd", aliases: ["Shenyang Geumpungri"] },
      { name: "Korea Sinjin Trading Corporation", aliases: ["Sinjin General Trading Corporation"] },
    ],
    summary:
      "OFAC says Andreyev and Kim Ung Sun facilitated hundreds of thousands of dollars in transfers for Chinyong, while Shenyang Geumpungri and Sinjin supported DPRK IT worker revenue generation.",
    indicators: ["Crypto-to-cash conversion", "Chinyong-linked front company", "DPRK IT worker delegation", "Sanctions designation"],
    link: "https://home.treasury.gov/news/press-releases/sb0230",
  },
  {
    id: "kmctc-bankers",
    title: "OFAC bankers and KMCTC IT delegation network",
    status: "OFAC-designated sanctions targets",
    date: "2025-11-04",
    sourceId: "treasury-2025-bankers",
    names: [
      { name: "Jang Kuk Chol", aliases: [] },
      { name: "Ho Jong Son", aliases: [] },
      { name: "Korea Mangyongdae Computer Technology Company", aliases: ["KMCTC"] },
      { name: "U Yong Su", aliases: [] },
      { name: "Ryujong Credit Bank", aliases: [] },
    ],
    summary:
      "OFAC says DPRK bankers helped manage cryptocurrency funds and that KMCTC operated IT worker delegations from Shenyang and Dandong using banking proxies.",
    indicators: ["Cryptocurrency fund management", "IT worker delegations in China", "Banking proxies", "Sanctions designation"],
    link: "https://home.treasury.gov/news/press-releases/sb0302",
  },
];

export const EXTRA_SOURCE_LINKS = {
  "treasury-2023-chinyong": {
    title: "Treasury Targets DPRK Malicious Cyber and Illicit IT Worker Activities",
    publisher: "U.S. Treasury OFAC",
    date: "2023-05-23",
    url: "https://home.treasury.gov/news/press-releases/jy1498",
  },
  "doj-2023-sim": {
    title: "North Korean Foreign Trade Bank Representative Charged in Crypto Laundering Conspiracies",
    publisher: "U.S. Department of Justice",
    date: "2023-04-24",
    url: "https://www.justice.gov/opa/pr/north-korean-foreign-trade-bank-representative-charged-crypto-laundering-conspiracies",
  },
};
